# special build for github
{% set data = load_setup_py_data(setup_file=RECIPE_DIR + "/../setup.py") %}

package:
  name: {{ data['name'] }}
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 1
  script_env:
    - RUNNER_WORKSPACE

requirements:
  host:
    - python
    - cython=0.29.37
    - pip
    - wheel

  build:
    - {{ compiler('cxx') }}
    - boost-cpp

  run:
    - python

test:
  import:
    - larch.pickle


about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
