{% set data = load_setup_py_data(setup_file=RECIPE_DIR + "/../setup.py") %}

package:
  name: {{ data['name'] }}
  version: {{ data['version'] }}

source:
  path: ..

build_windows: &bwindows
  number: 0
  preserve_egg_dir: True
  script: |
    rmdir /Q /S dist
    if errorlevel 1 exit 1

    rmdir /Q /S build
    if errorlevel 1 exit 1

    "{{ PYTHON }}" setup.py bdist_egg --exclude-source-files
    if errorlevel 1 exit 1

    for /r %%i in (dist\*.egg) do "{{ PYTHON }}" -m easy_install --no-deps %%i
    if errorlevel 1 exit 1

    for /R %%f in ($SP_DIR\*) do del %%f

build_unix: &bunix
  number: 0
  preserve_egg_dir: True
  script: |
    rm -rf build
    rm -rf dist
    {{ PYTHON }} setup.py bdist_egg --exclude-source-files
    {{ PYTHON }} -m easy_install --no-deps dist/*.egg

build: *bwindows   # [win]
build: *bunix      # [not win]

requirements:
  host:
    - python
    - cython

  build:
    - {{ compiler('cxx') }}
    - boost-cpp
    - pip

test:
  requires:
    - python

  source_files:
    - tests

  commands:
    - python tests/test_pickle3.py -v

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
