{% set data = load_setup_py_data(setup_file=RECIPE_DIR + "/../setup.py") %}

package:
  name: {{ data['name'] }}
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - cython
    - pip

  build:
    - {{ compiler('cxx') }}
    - boost-cpp

  run:
    - python

test:
  import:
    - larch.pickle

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
