{% set data = load_setup_py_data(setup_file=RECIPE_DIR + "/../setup.py") %}

package:
  name: {{ data['name'] }}
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - cython
    - pip

  build:
    - {{ compiler('cxx') }}
    - boost-cpp

test:
  requires:
    - python

  source_files:
    - tests

  commands:
    - python tests/test_pickle3.py -v

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
