name: Build Wheel

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version

      - name: Install system dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y build-essential libboost-all-dev
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install visualstudio2019community --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools" -y
            choco install boost-msvc-$(python -c "import sys; print('14' if sys.version_info.major == 3 and sys.version_info.minor < 9 else '15')") --version=1.75.0 -y
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install boost
            brew install gcc  # Install GCC for C++ compilation
          fi

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython wheel

      - name: Build Wheel
        run: |
          python setup.py bdist_wheel

      - name: Upload Wheel
        uses: actions/upload-artifact@v2
        with:
          name: larch-pickle-wheel
          path: dist/*.whl
