name: Build packages for pip and conda.

on: workflow_dispatch
  #release:
  #  types: [published]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       python-version: ["3.10", "3.11", "3.12"]
    steps:
    - name: Get release
      id: get_release
      uses: thebritican/fetch-latest-release@v2.0.0
      env:
        GITHUB_TOKEN: ${{ github.token }}        
    - uses: actions/checkout@v4
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/Scripts >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install -y conda-build
    - name: build package with conda
      run: |
        conda build --python=${{ matrix.python-version }} github-build
    - uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: /home/runner/work/larch-pickle/*.whl
        overwrite: true
    - uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: /usr/share/miniconda/conda-bld/linux-64/larch*.bz2
        overwrite: true

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
       python-version: ["3.10", "3.11", "3.12"]
    steps:
    - name: Get release
      id: get_release
      uses: thebritican/fetch-latest-release@v2.0.0
      env:
        GITHUB_TOKEN: ${{ github.token }}        
    - uses: actions/checkout@v4
    - name: debug
      run: |
        gci env:* | sort-object name
    - name: Add conda to system path
      run: |
        # $env:CONDA is an environment variable pointing to the root of the miniconda directory
        echo $env:CONDA\Scripts >> $env:GITHUB_PATH
    - name: Conda update
      run: |
        conda update --all -y
    - name: Install dependencies
      run: |
        conda install -y conda-build
    - name: build package with conda
      run: |
        conda build --python=${{ matrix.python-version }} github-build
    - name: debug2
      run: |
        echo "workspace ${{ github.workspace }}"
        echo "runner_workspace ${{ runner.workspace }}"
        dir ${{ github.workspace }}
        dir ${{ runner.workspace }}
        dir D:\a\larch-pickle
    - uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ${{ runner.workspace }}\*.whl
        overwrite: true
    - uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: C:\Miniconda\conda-bld\win-64\larch*.bz2
        overwrite: true

  build-macos:
   runs-on: macos-latest
   strategy:
     matrix:
      python-version: ["3.10", "3.11", "3.12"]

   steps:
   - name: Get release
     id: get_release
     uses: thebritican/fetch-latest-release@v2.0.0
     env:
       GITHUB_TOKEN: ${{ github.token }}        
   - uses: actions/checkout@v4
   - name: Install boost
     uses: MarkusJx/install-boost@v2.4.5
     id: install-boost
     with:
        boost_version: 1.84.0
   - name: Xcode Select Version
     uses: mobiledevops/xcode-select-version-action@v1
     with:
       xcode-select-version: 14.2
   - uses: actions/setup-python@v5
     with:
       python-version: ${{ matrix.python-version }}
   - name: Install Python dependencies
     uses: py-actions/py-dependency-install@v4
     with:
       path: github-build/requirements.txt
   - name: build package
     run: |
       python setup.py bdist_wheel build_ext --include-dirs=`pwd`/boost/boost/include
   - uses: shogo82148/actions-upload-release-asset@v1
     with:
      upload_url: ${{ steps.get_release.outputs.upload_url }}
      asset_path: /Users/runner/work/larch-pickle/larch-pickle/dist/*.whl
      overwrite: true
   
