name: Build Wheel

on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libboost-all-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython wheel setuptools

      - name: Build Wheel
        run: |
          python setup.py bdist_wheel

      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: larch-pickle-wheel-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/*.whl
          if-no-files-found: error

  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ['3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          brew install boost
          brew install gcc

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython wheel setuptools

      - name: Build Wheel
        env:
          BOOST_DIR: /usr/local/opt/boost
        run: |
          python setup.py bdist_wheel

      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: larch-pickle-wheel-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/*.whl
          if-no-files-found: error
  
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          choco install visualstudio2022buildtools -y
          curl -L -o boost.zip https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.zip
          tar -xf boost.zip -C C:/local
          setx BOOST_ROOT C:/local/boost_1_75_0
          setx PATH "%PATH%;C:/local/boost_1_75_0"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython wheel setuptools

      - name: Build Wheel
        env:
          BOOST_DIR: C:\\local\\boost_1_75_0
        run: |
          python setup.py bdist_wheel

      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: larch-pickle-wheel-${{ runner.os }}-py${{ matrix.python-version }}
          path: dist/*.whl
          if-no-files-found: error
