name: Playground

on: workflow_dispatch

jobs:

  build-macos:
   runs-on: macos-latest
   strategy:
     matrix:
      python-version: ["3.12"]

   steps:
   - name: Get release
     id: get_release
     uses: thebritican/fetch-latest-release@v2.0.0
     env:
       GITHUB_TOKEN: ${{ github.token }}        
   - uses: actions/checkout@v4
   - name: Xcode Select Version
     uses: mobiledevops/xcode-select-version-action@v1
     with:
       xcode-select-version: 14.2
   - name: Add conda to system path
     run: |
       # $CONDA is an environment variable pointing to the root of the miniconda directory
       echo $CONDA/Scripts >> $GITHUB_PATH
   - name: Install dependencies
     run: |
       sudo conda install -y conda-build
   - name: build package with conda
     run: |
       sudo --preserve-env=RUNNER_WORKSPACE conda build --debug --python=${{ matrix.python-version }} github-build
   - uses: shogo82148/actions-upload-release-asset@v1
     with:
      upload_url: ${{ steps.get_release.outputs.upload_url }}
      asset_path: /Users/runner/work/larch-pickle/*.whl
      overwrite: true
   - uses: shogo82148/actions-upload-release-asset@v1
     with:
      upload_url: ${{ steps.get_release.outputs.upload_url }}
      asset_path: /usr/local/miniconda/conda-bld/osx-64/larch*.bz2
      overwrite: true

 
