name: Playground

on: workflow_dispatch

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [macos-14] # [ubuntu-latest, macos-13, macos-14, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          # CIBW_BUILD: cp310-* cp311-* cp312-* 
          CIBW_BUILD: cp312-* 
          CIBW_BEFORE_BUILD_LINUX: |
              yum install -y wget tar
              wget -nv -O boost_1_75_0.tar.gz https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.tar.gz
              tar -xzf boost_1_75_0.tar.gz
              cd boost_1_75_0
              ./bootstrap.sh
              ./b2 headers
              cp -r boost /usr/include
          CIBW_BEFORE_BUILD_WINDOWS: |
              powershell -Command "Invoke-WebRequest -Uri https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.zip -OutFile boost_1_75_0.zip"
              powershell -Command "Expand-Archive -Path boost_1_75_0.zip -DestinationPath ."
              cd boost_1_75_0
              bootstrap.bat
              b2 headers
              xcopy boost C:\boost /E /I /Y
          CIBW_BEFORE_BUILD_MACOS: |
              wget -nv -O boost_1_75_0.tar.gz https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.tar.gz
              tar -xzf boost_1_75_0.tar.gz
              cd boost_1_75_0
              ./bootstrap.sh
              ./b2 headers
              sudo cp -r boost /usr/local/include
          CIBW_ENVIRONMENT_MACOS: BOOST_DIR=/usr/local/boost/include

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
