name: Playground

on: workflow_dispatch

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
       python-version: ["3.12"]
    steps:
    - name: Get release
      id: get_release
      uses: thebritican/fetch-latest-release@v2.0.0
      env:
        GITHUB_TOKEN: ${{ github.token }}        
    - uses: actions/checkout@v4
    - name: debug
      run: |
        gci env:* | sort-object name
    - name: Add conda to system path
      run: |
        # $env:CONDA is an environment variable pointing to the root of the miniconda directory
        echo $env:CONDA\Scripts >> $env:GITHUB_PATH
    - name: Conda update
      run: |
        conda update --all -y
    - name: Install dependencies
      run: |
        conda install -y conda-build
    - name: build package with conda
      run: |
        conda build --python=${{ matrix.python-version }} github-build
    - name: debug2
      run: |
        echo "workspace ${{ github.workspace }}"
        echo "runner_workspace ${{ runner.workspace }}"
        dir ${{ github.workspace }}
        dir ${{ runner.workspace }}
        dir D:\a\larch-pickle
    - uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ${{ runner.workspace }}\*.whl
        overwrite: true
    - uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: C:\Miniconda\conda-bld\win-64\larch*.bz2
        overwrite: true
