name: Playground

on: workflow_dispatch

jobs:

  build-macos:
   runs-on: ubuntu-latest
   strategy:
     matrix:
      python-version: ["3.12"]

   steps:
   - name: Get release
     id: get_release
     uses: thebritican/fetch-latest-release@v2.0.0
     env:
       GITHUB_TOKEN: ${{ github.token }}        
   - uses: actions/checkout@v4

   - uses: actions/setup-python@v5
     with:
       python-version: '3.12'

   - name: Install Python dependencies
     uses: py-actions/py-dependency-install@v4
     with:
       path: github-build/requirements.txt
   - name: build package
     run: |
       python setup.py sdist

   - name: Debug
     run: |
       pwd
       ls
       echo "-------------------"
       ls dist
       echo "------------------"
   
   - uses: shogo82148/actions-upload-release-asset@v1
     with:
      upload_url: ${{ steps.get_release.outputs.upload_url }}
      asset_path: /Users/runner/work/larch-pickle/larch-pickle/dist/*.tar.gz
      overwrite: true
   
 
