name: Playground

on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libboost-all-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython wheel setuptools

      - name: Build Wheel
        run: |
          python setup.py bdist_wheel

      - name: Find first wheel file
        id: find_wheel
        run: |
          first_wheel=$(ls dist/*.whl | head -n 1)
          echo "wheel=$first_wheel" >> $GITHUB_ENV
          echo "wheel_base=$(basename $first_wheel)" >> $GITHUB_ENV

      - name: Get latest release draft
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const draftRelease = releases.data.find(release => release.draft);
            if (!draftRelease) {
              throw new Error('No draft release found');
            }
            core.setOutput('upload_url', draftRelease.upload_url);

      - name: Upload to release draft
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_UPLOAD }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ env.wheel }}
          asset_name: larch-pickle-wheel-${{ matrix.os }}-py${{ matrix.python-version }}
          asset_name: ${{ env.wheel_base }}
          asset_content_type: application/zip
