name: Playground

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Get release
      id: get_release
      uses: thebritican/fetch-latest-release@v2.0.0
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: create dist
      run: |
        mkdir dist
  
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: tags/${{ steps.get_release.outputs.tag_name }}
        file: '.*[.](whl|tar.gz)$'
        regex: true
        target: "dist/"

    - name: create dist
      run: |
        ls -R

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TESTPI_API_TOKEN }}
      run: |
        twine upload --verbose --repository testpypi dist/*
