name: Playground

on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libboost-all-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython wheel setuptools

      - name: Build Wheel
        run: |
          python setup.py bdist_wheel

      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: larch-pickle-wheel-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/*.whl
          if-no-files-found: error

      - name: Show
        run: |
          ls 
          echo "dist"
          ls dist
