name: Python Build and Upload

on: workflow_dispatch
  #release:
  #  types: [published]

jobs:
  build-macos:
   runs-on: macos-latest
   strategy:
     matrix:
      python-version: [3.9]

   steps:
   - uses: actions/checkout@v2
   - name: change xcode version
     run: |
       sudo xcode-select -switch /Applications/Xcode_11.7.app
   - name: Add conda to system path
     run: |
       # $CONDA is an environment variable pointing to the root of the miniconda directory
       echo $CONDA/Scripts >> $GITHUB_PATH
   - name: Install dependencies
     run: |
       sudo conda install -y conda-build
   - name: build package with conda
     run: |
       sudo --preserve-env=RUNNER_WORKSPACE conda build --python=${{ matrix.python-version }} github-build
   - uses: svenstaro/upload-release-action@v2
     with:
       repo_token: ${{ secrets.GITHUB_TOKEN }}
       file: /Users/runner/work/larch-pickle/*.whl
       file_glob: true
       tag: ${{ github.ref }}
       overwrite: true
       body: "python wheel for macos and python ${{ matrix.python-version }}"
