name: Python Build and Upload

on: workflow_dispatch
  #release:
  #  types: [published]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: DEBUG1
      run: |
        echo "---------------RUNNER_WORKSPACE------"
        echo $RUNNER_WORKSPACE
        ls $RUNNER_WORKSPACE
    - name: DEBUG2
      run: |
        echo "---------------conda------"
        echo $CONDA
        ls $CONDA
