name: Python Build and Upload

on: push
  #release:
  #  types: [published]

jobs:
  build-macos:
   runs-on: macos-latest
   strategy:
     matrix:
      python-version: [3.9]

   steps:
   - uses: actions/checkout@v2
   - name: DEBUG
     run: |
       echo "RUNNER_WORKSPACE $RUNNER_WORKSPACE"
       echo "CONDA $CONDA"
   
