name: Python Build and Upload

on: workflow_dispatch
  #release:
  #  types: [published]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/Scripts >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install -y conda-build
    - name: build package with conda
      run: |
        conda build --python=${{ matrix.python-version }} github-build
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/larch-pickle/*.whl
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /usr/share/miniconda/conda-bld/linux-64/larch*.bz2
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
