name: Publish Python to TestPypi
on: workflow_dispatch
jobs:  
  publish-to-testpypi:
    name: Publish Python distribution to TestPyPI
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/larch-pickle

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Get release
      id: get_release
      uses: thebritican/fetch-latest-release@v2.0.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: tags/${{ steps.get_release.outputs.tag_name }}
        file: '.*[.]whl'
        regex: true

    - name: Debug
      run: |
       pwd
       ls 
       echo "------------------"
       
