name: Publish Python to TestPypi
on: workflow_dispatch
jobs:  
  publish-to-testpypi:
    name: Publish Python distribution to TestPyPI
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      # url: https://test.pypi.org/p/larch-pickle
      url: https://pypi.org/p/larch-pickle

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Get release
      id: get_release
      uses: thebritican/fetch-latest-release@v2.0.0
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: create dist
      run: |
       mkdir dist
    
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: tags/${{ steps.get_release.outputs.tag_name }}
        file: '.*[.]whl$'
        regex: true
        target: "dist/dist"

    - name: Debug
      run: |
       pwd
       ls 
       echo "------------------"

    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # repository-url: https://test.pypi.org/legacy/
        verbose: true
        skip-existing: true
