name: Windows Test

on: push
  
jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
       python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - run: |
        gci env:* | sort-object name
